name       : python-pygithub
version    : '1.55'
release    : 5
source     :
    - https://github.com/PyGithub/PyGithub/archive/refs/tags/v1.55.tar.gz : c674e5cceba1f2cf0d7ea79da66cf31f1131e86c41cd66a2330890f74327c0e1
homepage   : https://github.com/PyGithub/PyGithub
license    : LGPL-3.0-or-later
component  : programming.python
summary    : Typed interactions with the GitHub API
description: |
    PyGitHub is a Python library to access the GitHub API and Github Enterprise API. This library enables you to manage GitHub resources such as repositories, user profiles, and organizations in your Python applications.
builddeps  :
    - python-deprecated
    - python-httpretty
    - python-pyjwt
    - python-pynacl
    - python-pytest
    - python-requests
    - python-six
    - python-wheel
rundeps    :
    - python-deprecated
    - python-pyjwt
    - python-pynacl
    - python-requests
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
