name       : python-pygithub
version    : '1.57'
release    : 7
source     :
    - https://github.com/PyGithub/PyGithub/archive/refs/tags/v1.57.tar.gz : 989f30d123eb86c27e69c23ce8f72c3a3391f1e66ecb54ee8cd033242d7aa064
homepage   : https://github.com/PyGithub/PyGithub
license    : LGPL-3.0-or-later
component  : programming.python
summary    : Typed interactions with the GitHub API
description: |
    PyGitHub is a Python library to access the GitHub API and Github Enterprise API. This library enables you to manage GitHub resources such as repositories, user profiles, and organizations in your Python applications.
builddeps  :
    - python-deprecated
    - python-httpretty
    - python-pyjwt
    - python-pynacl
    - python-pytest
    - python-requests
    - python-wheel
rundeps    :
    - python-deprecated
    - python-pyjwt
    - python-pynacl
    - python-requests
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
