name       : python-pygithub
version    : 1.43.8
release    : 2
source     :
    - https://files.pythonhosted.org/packages/13/66/5c510242526d162708ffc0c82fd5ba647886f07d7abcae8587adeec86411/PyGithub-1.43.8.tar.gz : db415a5aeb5ab1e4a3263b1a091b4f9ffbd85a12a06a0303d5bf083ce7c1b2c8
license    : LGPL-3.0-or-later
component  : programming.python
summary    : Typed interactions with the GitHub API
description: |
    PyGitHub is a Python library to access the GitHub API and Github Enterprise API. This library enables you to manage GitHub resources such as repositories, user profiles, and organizations in your Python applications.
builddeps  :
    - python-deprecated
    - python-pyjwt
    - python-requests
    - python-six
    - python-sphinx-rtd-theme
rundeps    :
    - python-deprecated
    - python-pyjwt
    - python-requests
    - python-six
    - python-sphinx-rtd-theme
build      : |
    %python3_setup
install    : |
    %python3_install
