name       : python-pygithub
version    : 1.58.2
release    : 8
source     :
    - https://files.pythonhosted.org/packages/source/P/PyGithub/PyGithub-1.58.2.tar.gz : 1e6b1b7afe31f75151fb81f7ab6b984a7188a852bdb123dbb9ae90023c3ce60f
homepage   : https://github.com/PyGithub/PyGithub
license    : LGPL-3.0-or-later
component  : programming.python
summary    : Typed interactions with the GitHub API
description: |
    PyGitHub is a Python library to access the GitHub API and Github Enterprise API. This library enables you to manage GitHub resources such as repositories, user profiles, and organizations in your Python applications.
builddeps  :
    - python-deprecated
    - python-httpretty
    - python-pyjwt
    - python-pynacl
    - python-pytest
    - python-requests
    - python-setuptools-scm
    - python-wheel
rundeps    :
    - python-deprecated
    - python-pyjwt
    - python-pynacl
    - python-requests
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
